### ISSUE TITLE
Cut back on the coin-granting reaction list

### ISSUE THREAD

**Issue by gwynne** [vapor/penny-bot#105]
The current list of emoji reactions which grant coins is:
```swift
        static let coinSignEmojis = [
            Constants.ServerEmojis.love.name,
            Constants.ServerEmojis.vapor.name,
            Constants.ServerEmojis.coin.name,
            Constants.ServerEmojis.doge.name,
            "🪙",
            "❤️", "💙", "💜", "🤍", "🤎", "🖤", "💛", "💚", "🧡",
            "💗", "💖", "💞", "❣️", "💓", "💘", "💝", "💕", "❤️‍🔥", "💟",
            "😍", "😻",
            "🚀", "🎉", "💯",
            "🙌", "🙌🏻", "🙌🏼", "🙌🏽", "🙌🏾", "🙌🏿",
            "🙏", "🙏🏻", "🙏🏼", "🙏🏽", "🙏🏾", "🙏🏿",
            "👌", "👌🏻", "👌🏼", "👌🏽", "👌🏾", "👌🏿",
            "👍", "👍🏻", "👍🏼", "👍🏽", "👍🏾", "👍🏿",
        ]
```
(per https://github.com/vapor/penny-bot/blob/main/Sources/Penny/Handlers/ReactionHandler/ReactionHandler.swift#L9-L23)

This is now becoming a bit noisy, and people are granting coins without meaning to. I propose this list:
```swift
       /// U+1F3FB EMOJI MODIFIER FITZPATRICK TYPE-1-2...TYPE-6
        private static let emojiSkins = ["","\u{1f3fb}","\u{1f3fc}","\u{1f3fd}","\u{1f3fe}","\u{1f3ff}"]
        /// U+2640 FEMALE SIGN, U+2642 MALE SIGN, U+200D ZWJ, U+FE0F VARIATION SELECTOR 16
        private static let emojiGenders = ["", "\u{200d}\u{2640}\u{fe0f}", "\u{200d}\u{2642}\u{fe0f}"]

       static let coinSignEmojis = [
            Constants.ServerEmojis.love.name,
            Constants.ServerEmojis.vapor.name,
            Constants.ServerEmojis.coin.name, "🪙",
            "❤️", "💙", "💜", "🤍", "🤎", "🖤", "💛", "💚", "🧡",
            "🩷", "🩶", "🩵", "💗", "💕", "😍", "😻", "🎉", "💯",
        ]
            + emojiSkins.map { "🙌\($0)" }
            + emojiSkins.map { "🙏\($0)" }
            + emojiSkins.map { "👍\($0)" }
            + emojiSkins.map { s in emojiGenders.map { g in "🙇\(s)\(g)" } }
```

(for the record, this, of course, yields the array `["vaporlove", "vapor", "coin", "🪙", "❤️", "💙", "💜", "🤍", "🤎", "🖤", "💛", "💚", "🧡", "🩷", "🩶", "🩵", "💗", "💕", "😍", "😻", "🎉", "💯", "🙌", "🙌🏻", "🙌🏼", "🙌🏽", "🙌🏾", "🙌🏿", "🙏", "🙏🏻", "🙏🏼", "🙏🏽", "🙏🏾", "🙏🏿", "👍", "👍🏻", "👍🏼", "👍🏽", "👍🏾", "👍🏿", "🙇", "🙇‍♀️", "🙇‍♂️", "🙇🏻", "🙇🏻‍♀️", "🙇🏻‍♂️", "🙇🏼", "🙇🏼‍♀️", "🙇🏼‍♂️", "🙇🏽", "🙇🏽‍♀️", "🙇🏽‍♂️", "🙇🏾", "🙇🏾‍♀️", "🙇🏾‍♂️", "🙇🏿", "🙇🏿‍♀️", "🙇🏿‍♂️"]`)

**Comment by gwynne** [comment]
For completeness: The new list removes these emoji:

- 👌 and variants
- 🚀
- 💟
- 💖💞❣️💓💘💝❤️‍🔥
- Doge

And adds:

- 🩷🩶🩵
- 🙇 and its 17 skin tone and gender variants

**Comment by 0xTim** [comment]
Happy to continue tweaking. I'd say 🚀 should probably stay and I'm happy to remove 👍 as I think that could cause confusion

**Comment by ptoffy** [comment]
RIP doge 🥲

**Comment by tkrajacic** [comment]
Noooooooooo 😭

**Comment by MahdiBM** [comment]
Objections 😛:
* What @0xTim said.
* 👌 Should stay.
* Doge should stay. People who use it already know it gives a coin. It's not something new comers would use and get confused.
* 🙇 fine, but who even uses that anyway?!

**Comment by MahdiBM** [comment]
@gwynne @0xTim what is the conclusion on this? :eyes:

**Comment by 0xTim** [comment]
My vote is @gwynne suggestions but remove 👍 and add back 🚀

**Comment by MahdiBM** [comment]
Fine but i'm also keeping doge 😁

**Comment by ptoffy** [comment]
> Fine but i'm also keeping doge 😁

Not the hero we deserve, but the hero we need

**Comment by MahdiBM** [comment]
this is resolved btw, what Gwynne said with Tim and my final changes.
