### ISSUE TITLE
Slash commands for linking discord and github profiles together

### ISSUE THREAD

**Issue by BennyDeBock** [vapor/penny-bot#13]
It would be great if the bot would have some ways to link the Discord to a certain Github account and the other way around.

This way, if in the future coins will be given on a successful PR, we would be able to merge the two accounts into one in the database if people have not linked their Github yet.

These two cases are for if you happen to change accounts on github/discord because you got locked out for some reason. This way, you do not lose your coins.

Two functions have already been provided, but not implemented yet.
https://github.com/vapor/penny-bot/blob/main/CODE/Sources/PennySHARED/Repositories/DynamoUserRepository.swift#L89
https://github.com/vapor/penny-bot/blob/main/CODE/Sources/PennySHARED/Repositories/DynamoUserRepository.swift#L101

**Comment by MahdiBM** [comment]
since @ptoffy requested this i'm going to assign it to him just because why not
