### ISSUE TITLE
Receiving coins on a successful PR anywhere in the Vapor Ecosystem

### ISSUE THREAD

**Issue by BennyDeBock** [vapor/penny-bot#14]
It would be great if people were also able to collect some coins when they successfully submit a PR that is then merged.

This would consist of:
- A github event happened
- There is a check to see if it's a merge of a pull request
- The github id provided in the event is searched amongst the users
    - IF the user does not exist, create the specified user
- add a coin to that user
- display a message in the discord `#thanks` channel

**Comment by MahdiBM** [comment]
This should be doable with what we're doing in #51 ... we should be able to add it to the new GHHooks lambda which i'll do soon probably

**Comment by MahdiBM** [comment]
Didn't notice but i've already resolved this.
