### ISSUE TITLE
Create Deployment Stack

### ISSUE THREAD

**Issue by 0xTim** [vapor/penny-bot#2]
We should create a CloudFormation stack that can be used to deploy the API code to Lambda. For now it just needs to:
* Create the lambda
* Reference the lambda source
* Create an API Gateway to route the API calls through to the Lambda

**Comment by BennyDeBock** [comment]
On a new deployment (change) the bot responds twice as both the new and the old image are loaded still. 

TODO
Find out what's causing this behaviour to happen

**Comment by BennyDeBock** [comment]
finished
