### ISSUE TITLE
Execute swift code using Penny

### ISSUE THREAD

**Issue by MahdiBM** [vapor/penny-bot#41]
Penny should be able to execute simple Swift code and show the code's result.
We should also make sure the execution environment is sandboxed and that the execution doesn't take forever.

This would be a cool feature, although might not be too useful.

**Comment by gwynne** [comment]
I tend to think this has too low a cost/benefit ratio to be worth it, tbh

**Comment by MahdiBM** [comment]
Yes, but it does look cool 😎

**Comment by 0xTim** [comment]
Yeah I would say this is out of scope for Penny

**Comment by MahdiBM** [comment]
FYI It's not even on the TODO list. I know it won't be too useful, but might just want to implement it for the "cool" aspect 😅 and the occasional semi-usefulness since I've seen other communities have something like this too.

**Comment by MahdiBM** [comment]
And also if it "makes sense" e.g. financially etc...

**Comment by gwynne** [comment]
Yeah, no, I think we're gonna file this one under "wishful thinking". It's questionable whether Swift is even really amenable to this, it's not a scripting language (or at the very least, not a concise one).
