### ISSUE TITLE
Posting releases in Discord should be handled from the release events

### ISSUE THREAD

**Issue by gwynne** [vapor/penny-bot#74]
Right now, releases are reported to the `#release` Discord channel as a side effect of the pull request event handler creating the release. These two actions should be separate so that Penny will automatically report all releases in the org(s), not just ones it created itself.

**Comment by MahdiBM** [comment]
Done in https://github.com/vapor/penny-bot/commit/a018f98d97c8ec9648addc55531ce9c16a2a16cf.
