### ISSUE TITLE
Better handling of user-table transactions

### ISSUE THREAD

**Issue by MahdiBM** [vapor/penny-bot#76]
The user-table transaction can all happen through a central place like a lambda, currently named "UsersLambda".

Alternatively, we can just remove the lambda and use the `UserService` so every place can access the table just on their own. This will need giving table perms to all different places that use the service.

**Comment by MahdiBM** [comment]
@0xTim What do you think we should do about this one? Which way should we go?

**Comment by 0xTim** [comment]
Only one thing should be accessing the table, either a lambda or service. We shouldn't have multiple services or lambdas using the same table otherwise we have a distributed monolith

**Comment by MahdiBM** [comment]
Moved everything related to Users stuff, to only use the "UsersLambda" in https://github.com/vapor/penny-bot/commit/f833099fdd61adfcf6de45b4b4dbd2e3417b2952
