### ISSUE TITLE
Multiple matching reactions to the same message should each grant coins

### ISSUE THREAD

**Issue by gwynne** [vapor/penny-bot#78]
Currently if the same user adds two or more different coin-granting reactions to the same post, only the first one grants a coin. It's particularly notable that if a "super" reaction (which ought to grant 3 coins) is added after a "normal" one, the user still only gets one coin.

This should be distinguished from the same user adding and removing the same reaction to the same message over and over, to avoid users being able to repeatedly click/tap the reaction button over and over to spam coins.

**Comment by MahdiBM** [comment]
Resolved in https://github.com/vapor/penny-bot/commit/1fd78d6341d851e30b5841fe5dca93ca895a1fbe.
