### ISSUE TITLE
Respond to `push` events by calling workflows

### ISSUE THREAD

**Issue by gwynne** [vapor/penny-bot#84]
Right now, the `projectboard.yml` and `api-docs.yml` workflows must exist in every repository even though all they do is call the reusable workflows that do the actual work. Penny doesn't have to do the work those workflows do; all that needs to happen is for the `push` events to trigger equivalent `workflow_dispatch` events so that the reusable workflows get called organization-wide without having to update every damn repo if anything ever changes about the call sequence. Details:

- On `push` to `main` for all repos:
  1. Get the results of executing `find repo -name '*.docc' -type d` for the pushed repo (i.e. list of DocC catalogs in the repo). If there aren't any, do nothing.
  2. If there are, send a `workflow_dispatch` to `vapor/api-docs/.github/workflows/build-and-deploy-docs-workflow.yml@main` with inputs:
      ```
      repository: repo_owner/repo_name
      package_name: <result of (swift package describe -type json | jq '.name')>
      modules: <results of find command.map { basename(dirname($0)) }.joined(separator: ",">
      pathsToInvalidate: `modules list.map { "\($0.lowercased())/*" }.joined(separator: " ")
      ```
- On `issues` events (types `reopened, closed, labeled, unlabeled, assigned, unassigned`) for all repos, send a `workflow_dispatch` to `vapor/ci/.github/workflows/update-project-boards-for-issue.yml@main` with event payload, no parameters needed.

**Comment by MahdiBM** [comment]
I think it's generally a good idea to have some generic functionality so we can just set up penny to call workflows instead of having to duplicate workflows across all repos and then having to edit all those workflows the next time something needs to change.

**Comment by MahdiBM** [comment]
Something like what the reusable CI does for example.
It would also be useful for the incoming swift-format stuff, if we ever come to conclusion that it's useable for us.

**Comment by gwynne** [comment]
This issue was actually suggesting that penny itself invoke the reusable workflows - but I looked into it a bit further and having the bot invoke the workflows via `workflow_dispatch` is problematic versus the existing invocation by `workflow_call` mechanism, mostly due to the loss of context. In reality it would only be viable where Penny can replace the reusable workflows entirely - which is certainly possible for the project boards thing, but may not be practical for the API docs.

**Comment by MahdiBM** [comment]
I haven't investigated the issue yet so not sure what we can/should do yet.

**Comment by MahdiBM** [comment]
Wait you closed the issue 😅
I'm still going to look into how we can have Penny call workflows. Again, not sure at all what's possible and what's not.
