### ISSUE TITLE
When editing or posting messages due to an issue being closed, Penny does not report who closed it

### ISSUE THREAD

**Issue by gwynne** [vapor/penny-bot#95]
For example, Penny posted this message:
<img alt="Screenshot 2023-08-13 at 04 45 29" src="https://github.com/vapor/penny-bot/assets/1130717/1ccc1c11-49f2-4b60-a93f-35503a63974d">

Unless one stops to think about it, this reads a lot like it was BdeBock who actually closed the issue, while in fact they are the OP and it was @MahdiBM who closed it.

**Comment by MahdiBM** [comment]
It only reposts if a message doesn't already exist for the issue/pr.

**Comment by MahdiBM** [comment]
It's suboptimal, i'm open to suggestions.

**Comment by gwynne** [comment]
> It only reposts if a message doesn't already exist for the issue/pr.

That's not really the issue - even if it edits in-place, the same visual confusion results.
